name: audio_books
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - click=7.1.2
  - flask=1.1.2
  - itsdangerous=1.1.0
  - jinja2=2.11.3
  - markupsafe=1.1.1
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.8.3
  - setuptools=52.0.0
  - sqlite=3.35.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - comtypes==1.1.10
    - joblib==1.0.1
    - nltk==3.6.2
    - numpy==1.20.2
    - opencv-python==4.5.1.48
    - pdf2image==1.14.0
    - pillow==8.2.0
    - pypdf2==1.26.0
    - pypiwin32==223
    - pytesseract==0.3.7
    - pyttsx3==2.90
    - pywin32==300
    - regex==2021.4.4
    - tqdm==4.60.0
    - slate3k==0.5.3
